recourse_methods:
  ar:
    hyperparams:
      fs_size: 150
  cem:
    hyperparams:
      batch_size: 1
      kappa: 0.1
      init_learning_rate: 0.01
      binary_search_steps: 9
      max_iterations: 100
      initial_const: 10
      beta: 0.9
      gamma: 0.0
      mode: "PN"
      num_classes: 2
      ae_params:
        h1: 20
        h2: 10
        d: 7
        train_ae: True
        epochs: 5
  cem-vae:
    hyperparams:
      batch_size: 1
      kappa: 0.1
      init_learning_rate: 0.01
      binary_search_steps: 9
      max_iterations: 100
      initial_const: 10
      beta: 0.0
      gamma: 6.0
      mode: "PN"
      num_classes: 2
      ae_params:
        h1: 20
        h2: 10
        d: 7
        train_ae: True
        epochs: 5
  clue:
    hyperparams:
      train_vae: True
      width: 10
      depth: 3
      latent_dim: 12
      batch_size: 64
      epochs: 1
      lr: 0.001
      early_stop: 10
  dice:
    hyperparams:
      num: 1
      desired_class: 1
  face_knn:
    hyperparams:
      mode: "knn"
      fraction: 0.15
  face_epsilon:
    hyperparams:
      mode: "epsilon"
      fraction: 0.15
  gs:
    hyperparams:
  wachter:
    hyperparams:
      loss_type: "BCE"
      binary_cat_features: False
