version: 1
formatters:
  simple:
    format: "%(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  sampleLogger:
    level: INFO
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
