version: 1
formatters:
  simple:
    format: "[%(levelname)s] %(message)s [%(filename)s %(funcName)s]"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  tensorflow:
    level: WARN
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
